image: node:10-alpine # use nodejs v10 LTS
cache:
  paths:
    - node_modules/

before_script:
  - npm install hexo-cli -g
  - npm install

pages:
  script:
    - hexo clean
    - hexo generate
    - hexo d
  artifacts:
    paths:
      - public
  only:
    - main